import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import Box from '@mui/material/Box';

import HeaderNavigation from '@/components/layout/Header'
import Sidebar from '@/components/layout/Sidebar';
import Footer from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <AppRouterCacheProvider>
            <HeaderNavigation />
            <Box sx={{
              "@media screen and (min-width:600px)": {
                display: 'flex',
              },
              minHeight: '100vh'
            }}>
              {/* Main Content */}
              <Box
                component="main"
                sx={{
                  flex: 7, // メイン記事エリアの幅
                  padding: 2,
                  display: 'flex',
                  flexDirection: 'column',
                  overflow: 'auto',
                }}
              >
                {children}
              </Box>
              {/* Sidebar */}
              <Box
                component="aside"
                sx={{
                  flex: 3, // サイドバーの幅
                  // backgroundColor: '#f4f4f4',
                  display: 'flex',
                  flexDirection: 'column',
                  margin: "20px 0"
                }}
              >
                <Sidebar />
              </Box>
            </Box>
            <Footer />
          </AppRouterCacheProvider>
      </body>
    </html>
  )
}
