import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import { AuthProvider } from "@/contexts/AuthProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Header />
          <div className="mx-auto flex w-full max-w-5xl gap-8 px-16 py-12">
            <main className="min-w-0 flex-1">
              {children}
            </main>
            <div className="hidden w-64 shrink-0 lg:block">
              <Sidebar />
            </div>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
